name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_printed_messages.py
      id: tests-test-01-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_01_printed_messages.py
        timeout: 30
        max-score: 9
    - name: tests/test_02_pokemon_class.py
      id: tests-test-02-pokemon-class-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-pokemon-class
        setup-command: ''
        command: python -m pytest -v tests/test_02_pokemon_class.py
        timeout: 30
        max-score: 15
    - name: tests/test_03_move_class.py
      id: tests-test-03-move-class-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-move-class
        setup-command: ''
        command: python -m pytest -v tests/test_03_move_class.py
        timeout: 30
        max-score: 15
    - name: tests/test_04_pokemon_get_info.py
      id: tests-test-04-pokemon-get-info-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-pokemon-get-info
        setup-command: ''
        command: python -m pytest -v tests/test_04_pokemon_get_info.py
        timeout: 30
        max-score: 15
    - name: tests/test_05_pokemon_heal.py
      id: tests-test-05-pokemon-heal-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-pokemon-heal
        setup-command: ''
        command: python -m pytest -v tests/test_05_pokemon_heal.py
        timeout: 30
        max-score: 15
    - name: tests/test_06_move_get_info.py
      id: tests-test-06-move-get-info-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-move-get-info
        setup-command: ''
        command: python -m pytest -v tests/test_06_move_get_info.py
        timeout: 30
        max-score: 15
    - name: tests/test_07_move_generate_attack_value.py
      id: tests-test-07-move-generate-attack-value-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-move-generate-attack-value
        setup-command: ''
        command: python -m pytest -v tests/test_07_move_generate_attack_value.py
        timeout: 30
        max-score: 15
    - name: tests/test_08_sufficient_comments.py
      id: tests-test-08-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-08-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_08_sufficient_comments.py
        timeout: 30
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-01-printed-messages-py.outputs.result}}
        TESTS-TEST-02-POKEMON-CLASS-PY_RESULTS: ${{steps.tests-test-02-pokemon-class-py.outputs.result}}
        TESTS-TEST-03-MOVE-CLASS-PY_RESULTS: ${{steps.tests-test-03-move-class-py.outputs.result}}
        TESTS-TEST-04-POKEMON-GET-INFO-PY_RESULTS: ${{steps.tests-test-04-pokemon-get-info-py.outputs.result}}
        TESTS-TEST-05-POKEMON-HEAL-PY_RESULTS: ${{steps.tests-test-05-pokemon-heal-py.outputs.result}}
        TESTS-TEST-06-MOVE-GET-INFO-PY_RESULTS: ${{steps.tests-test-06-move-get-info-py.outputs.result}}
        TESTS-TEST-07-MOVE-GENERATE-ATTACK-VALUE-PY_RESULTS: ${{steps.tests-test-07-move-generate-attack-value-py.outputs.result}}
        TESTS-TEST-08-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-08-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-printed-messages-py,tests-test-02-pokemon-class-py,tests-test-03-move-class-py,tests-test-04-pokemon-get-info-py,tests-test-05-pokemon-heal-py,tests-test-06-move-get-info-py,tests-test-07-move-generate-attack-value-py,tests-test-08-sufficient-comments-py
